name: python-flask-api-mockup
services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        - VERSION=1.0.0
    container_name: python-flask-api-mockup-container
    volumes:
      - ..:/workspace
      - /etc/hosts:/etc/hosts
    networks:
      - simple-python-flask-api-mockup-network
    command: ["sleep", "infinity"]
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - simple-python-flask-api-mockup-network

networks:
  simple-python-flask-api-mockup-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
