name: python-flask-api-mockup
services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/app.dockerfile
      args:
        - VERSION=1.0.0
        - APP_ENV_TYPE=dev
    container_name: "python-flask-api-mockup-container"
    volumes:
      - ..:/workspace
      - /etc/hosts:/etc/hosts
    networks:
      - simple-python-flask-api-mockup-network
    command: ["sleep", "infinity"]
  
  mysql:
    build:
      context: ..
      dockerfile: ./.devcontainer/mysql.dockerfile
    container_name: "python-flask-api-mockup-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    networks:
      - simple-python-flask-api-mockup-network

networks:
  simple-python-flask-api-mockup-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
